### ISSUE TITLE
Baseline Resolver issue on MzMine 4.2.0

### ISSUE THREAD

**Issue by ybsk0424** [mzmine/mzmine#1994]
Hello,

I am experiencing an issue with loading a specific module class in mzMine. The error message I receive is:

"Cannot load module class io.github.mzmine.modules.dataprocessing.featdet_chromatogramdeconvolution.baseline.BaselineFeatureResolverModule"

Could anyone help me understand what might be causing this error and how to resolve it?

Thank you for your assistance!

**Comment by ansgarkorf** [comment]
Hi,
can you please add a bit more context? 
What version do you use?
When does the error occur?

Please provide the requested information when reporting an issue, otherwise it is very difficult to help:
### Basic information

* My operating system and version:
* My mzmine version: 

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by ybsk0424** [comment]
![error message](https://github.com/user-attachments/assets/7e4d59fa-1178-4c0d-ab57-7a448ff7f20f)
[mzmine_0_0.log](https://github.com/user-attachments/files/16453768/mzmine_0_0.log)
Hi,

Here is the additional information requested regarding the issue I'm experiencing with mzMine:

Operating System and Version:

Windows 11 Enterprise, 64-bit operating system, x64-based processor
12th Gen Intel(R) Core(TM) i7-1265U 1.80 GHz
16.0 GB RAM
Windows Feature Experience Pack 
mzMine Version: mzMine 4.2.0


Description:

I encounter the error "Cannot load module class io.github.mzmine.modules.dataprocessing.featdet_chromatogramdeconvolution.baseline.BaselineFeatureResolverModule" when I try to use the Baseline Feature Resolver module. 

I cannot choose parameter values, it just give me this error. I have attached the screenshot, log file, my project file. These are GC-EI Low resolution chromatograms. 

Here is the link for the project file, it will expire in 1 week: https://we.tl/t-DOv0XU6qNm

I hope this information helps to diagnose the issue. Please let me know if any additional information is needed.

Thank you for your assistance!

**Comment by ansgarkorf** [comment]
Hi,
thanks a lot for sharing the information. Everything looks fine, except that we missed to remove the menu entry for the baseline resolver module... sorry for that. We will remove the menu entry in the next version.
In your project you successfully used the local minimum resolver, which we recommend to use. Do you get acceptable results when you try to use a batch generated from the mzwizard?
Is there a reason you prefer to use the baseline resolver? We found it not to be robust enough compared to e.g. local minimum resolver.
kind regards,
Ansgar

**Comment by ybsk0424** [comment]
Hi Ansgar,

Thank you very much for your comment and for addressing the issue with the menu entry for the baseline resolver module. I look forward to the update.

Regarding the mzWizard, I did try using the batch generated by it but found that I wasn't completely confident in its effectiveness for my specific needs. As a result, I have decided to stop using it for now. However, I have been using the local minimum resolver as you recommended, and I am pleased with the results it provides. 

Thank you for the recommendations. It’s been very helpful.

Kind regards,

Yonca
