### ISSUE TITLE
Cannot run previously established workflows 

### ISSUE THREAD

**Issue by ddlidded** [mzmine/mzmine#2105]
### Basic information

* My operating system and version: Mac 15.1
* My mzmine version: 4.3

### What happened

When attempting to run various mzxml files through the default workflow wizard configurator, I am getting this error repeaditly and am not sure where I am going wrong or if this is a glitch / bug? I have attached the log and attached a link to access the files in question (project)

Link to Exported Log File: [MZ-Log File.docx](https://github.com/user-attachments/files/17189353/MZ-Log.File.docx)
Link to Demo Project File: [Demo-Project.mzmine](https://od.lk/d/NDBfMTA3NjcwMjc0Xw/demo-project.mzmine)

Additional images requested of the error messages are also included below.

<img width="1176" alt="Screenshot 2024-09-30 at 5 05 53 AM" src="https://github.com/user-attachments/assets/406b1820-919b-45d3-8f23-0a75a7bb5dbc">
<img width="1231" alt="Screenshot 2024-09-30 at 5 08 51 AM" src="https://github.com/user-attachments/assets/461a13fe-6888-4437-a6bc-e8f26a3f8573">

Hope this helps.

**Comment by SteffenHeu** [comment]
Hi,

the second issue usually appears when the metaCorrelate step searches for more samples than there are currently loaded. E.g. the batch was designed to require at least 3 samples due to replicates or so, but now only a single file is processed. The same applies to previusly established wizard settings.

**Comment by SteffenHeu** [comment]
The other issue appears due to a bug that we will fix in the next version, thanks for the report.

However, i'm not confident that you can open the project again, because the data file names contain illegal characters `NaïveD3-ser-donor1_pos.mzXML`. I'm wondering how they were loaded in the first place. We will probably implement a check so this cannot happen. The easy fix should be replacing the ï with a regular i.
