### ISSUE TITLE
Issue import .mzML files converted from .raw files

### ISSUE THREAD

**Issue by saradbn** [mzmine/mzmine#2175]
### **Basic information**

* My operating system and version: Windows10
* My mzmine version: 4.3.0

### **What happened**

* I converted the .raw files (Waters, IM-MSe) into .mzML files, using data connect. Then, I imported these .mzML files in mzmine, but they all appeared having an error signal and seemed to be empty.
<img width="1233" alt="Capture" src="https://github.com/user-attachments/assets/79b64ad8-1dfa-4ee4-89d4-1212a7329d96">

* Is there anything I should try to fix this issue?
Thank you in advance!

**Comment by SteffenHeu** [comment]
Hi,

the issue is that mzml files do not store the accumulated frame spectra. therefore, we cannot display anything in the chromatogram and frame plots. 
To fix the issue, you need to run mass detection and mobility scan merging for the data file. Bot steps are done automatically, if the file is imported from the mzwizard.

**Comment by saradbn** [comment]
Hi,

thank you for your help. I have now used mzwizard, but the message reported in the image below appeared and the error signal was still present close to the file name in the "MS data files" section.
<img width="307" alt="Issue_2" src="https://github.com/user-attachments/assets/17d1723d-10a7-443c-ab1a-1e02b52028a8">
Do you have any suggestion on how I try to fix this issue?

Thank you in advance!

**Comment by SteffenHeu** [comment]
Hi, just click yes
