### ISSUE TITLE
Spectral library matching in 4.4.3

### ISSUE THREAD

**Issue by SergioERamos** [mzmine/mzmine#2284]
### Basic information

* Windows 10 Enterprise
* My mzmine version: 4.4.3 and 4.3.0

### What happened
Hello guys. I tried to run my batch mode with exactly the same data in both mentioned versions of MZmine, and found that in 4.4.3 there is a problem that causes an error in the spectral library search step. 

Needless to say, my batch mode and data works flawless in v4.3.0. As you can see in the screenshots. My last step is the module NIST MS search. 

In MZmine v4.4.3, due to the error, I do not get a Spectral match in the Aligned feature list peak. Interestingly, if I run the NIST MS search by going to Feature list methods > Annotation > search spectra > NIST MS search, then I do get Spectral matches in the same Aligned feature list.

Parameters among values are the same, as shown in the screenshots. The data is just 3 samples of a much larger dataset. I want to understand what causes the problem and what is different between my two versions of MZmine before I apply my batch mode to the entire dataset which takes a long time to process (GCMS-EI data).
Please, let me know how else can I help, and thank you so much!

The files and log data are here: https://drive.google.com/drive/folders/1uMsx4waFyvpyoaTJmORCA3zFy0l7fTaB

Screenshots here

![Capture0001](https://github.com/user-attachments/assets/3603b730-c484-4335-89fc-eef87a086478)
![Capture0002](https://github.com/user-attachments/assets/3317979a-3a8c-46eb-9a47-0ee5c66df6ec)
![Capture0003](https://github.com/user-attachments/assets/ce479c43-1ab1-4415-bf0c-f2a8c01fd5dc)
![Capture0004](https://github.com/user-attachments/assets/06351f6f-55db-4642-9532-6c3decdcebf0)
![Capture0005](https://github.com/user-attachments/assets/c55c8e46-d785-41df-adfb-45f3aed69745)
![Capture0006](https://github.com/user-attachments/assets/791ea958-c9b4-4538-8185-c1e5da39ba84)
![Capture0007](https://github.com/user-attachments/assets/1b59820c-13b6-4c66-b21e-dec41840d01e)
![Capture0008](https://github.com/user-attachments/assets/ac181ff8-f580-4cb5-90c6-90025167ea2b)
![Capture0009](https://github.com/user-attachments/assets/40bd7b9a-298b-4611-b710-db54a1d6dd21)
![Capture0010](https://github.com/user-attachments/assets/aab9b6e8-4fca-459a-889a-6bc1302a0ee9)
![Capture0011](https://github.com/user-attachments/assets/c1ae29a4-e629-4b94-9468-1adeb091c45b)
![Capture0012](https://github.com/user-attachments/assets/8173a0f4-3764-415e-8cc1-5a1bafc58edb)
![Capture0013](https://github.com/user-attachments/assets/c49ff7a9-171b-4c7a-921b-b4a173cde22f)

**Comment by SteffenHeu** [comment]
I have sent an access request to you.

**Comment by SteffenHeu** [comment]
hi,

i've had a look and it seems you are not importing any spectral libraries and thus the step fails. We change the internal selection of spectral libraries a bit, that's why it fails with an error now and before just went through even though there were no libraries.
The error message needs some more explaination though.

Long story short: Unless you import some local libraries, you can remove the spectral library search step. The nist ms search is independent of that and should work as soon as the library search step is removed or you added some libraries.

**Comment by robinschmid** [comment]
Also try changing the Molecular networking algorithm to Cosine similarity (GC-EI-MS). This should give better results

**Comment by SteffenHeu** [comment]
You can use both and they are complementary. The problem is that your workflow did not select any spectral libraries, so there was nothing to search, thus the error.

You would add a library here in the lower field or in the wizard:
![393299665-3603b730-c484-4335-89fc-eef87a086478](https://github.com/user-attachments/assets/8cfc4ee8-6849-4a84-9d38-9266d7ef9c23)
